package com.zte.mcrm.system.access.workflow.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ThreadExampleVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SIEBEL.CX_THREAD_REQ
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SIEBEL.CX_THREAD_REQ
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SIEBEL.CX_THREAD_REQ
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIEBEL.CX_THREAD_REQ
     *
     * @mbggenerated
     */
    public ThreadExampleVO() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIEBEL.CX_THREAD_REQ
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIEBEL.CX_THREAD_REQ
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIEBEL.CX_THREAD_REQ
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIEBEL.CX_THREAD_REQ
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIEBEL.CX_THREAD_REQ
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIEBEL.CX_THREAD_REQ
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIEBEL.CX_THREAD_REQ
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIEBEL.CX_THREAD_REQ
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIEBEL.CX_THREAD_REQ
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SIEBEL.CX_THREAD_REQ
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SIEBEL.CX_THREAD_REQ
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andRowIdIsNull() {
            addCriterion("ROW_ID is null");
            return (Criteria) this;
        }

        public Criteria andRowIdIsNotNull() {
            addCriterion("ROW_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRowIdEqualTo(String value) {
            addCriterion("ROW_ID =", value, "rowId");
            return (Criteria) this;
        }

        public Criteria andRowIdNotEqualTo(String value) {
            addCriterion("ROW_ID <>", value, "rowId");
            return (Criteria) this;
        }

        public Criteria andRowIdGreaterThan(String value) {
            addCriterion("ROW_ID >", value, "rowId");
            return (Criteria) this;
        }

        public Criteria andRowIdGreaterThanOrEqualTo(String value) {
            addCriterion("ROW_ID >=", value, "rowId");
            return (Criteria) this;
        }

        public Criteria andRowIdLessThan(String value) {
            addCriterion("ROW_ID <", value, "rowId");
            return (Criteria) this;
        }

        public Criteria andRowIdLessThanOrEqualTo(String value) {
            addCriterion("ROW_ID <=", value, "rowId");
            return (Criteria) this;
        }

        public Criteria andRowIdLike(String value) {
            addCriterion("ROW_ID like", value, "rowId");
            return (Criteria) this;
        }

        public Criteria andRowIdNotLike(String value) {
            addCriterion("ROW_ID not like", value, "rowId");
            return (Criteria) this;
        }

        public Criteria andRowIdIn(List<String> values) {
            addCriterion("ROW_ID in", values, "rowId");
            return (Criteria) this;
        }

        public Criteria andRowIdNotIn(List<String> values) {
            addCriterion("ROW_ID not in", values, "rowId");
            return (Criteria) this;
        }

        public Criteria andRowIdBetween(String value1, String value2) {
            addCriterion("ROW_ID between", value1, value2, "rowId");
            return (Criteria) this;
        }

        public Criteria andRowIdNotBetween(String value1, String value2) {
            addCriterion("ROW_ID not between", value1, value2, "rowId");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("CREATED is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("CREATED is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterionForJDBCDate("CREATED =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterionForJDBCDate("CREATED <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterionForJDBCDate("CREATED >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATED >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterionForJDBCDate("CREATED <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATED <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterionForJDBCDate("CREATED in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterionForJDBCDate("CREATED not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATED between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATED not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("CREATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("CREATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("CREATED_BY =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("CREATED_BY <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("CREATED_BY >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("CREATED_BY >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("CREATED_BY <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("CREATED_BY <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("CREATED_BY like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("CREATED_BY not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("CREATED_BY in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("CREATED_BY not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("CREATED_BY between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("CREATED_BY not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdIsNull() {
            addCriterion("LAST_UPD is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdIsNotNull() {
            addCriterion("LAST_UPD is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdEqualTo(Date value) {
            addCriterionForJDBCDate("LAST_UPD =", value, "lastUpd");
            return (Criteria) this;
        }

        public Criteria andLastUpdNotEqualTo(Date value) {
            addCriterionForJDBCDate("LAST_UPD <>", value, "lastUpd");
            return (Criteria) this;
        }

        public Criteria andLastUpdGreaterThan(Date value) {
            addCriterionForJDBCDate("LAST_UPD >", value, "lastUpd");
            return (Criteria) this;
        }

        public Criteria andLastUpdGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LAST_UPD >=", value, "lastUpd");
            return (Criteria) this;
        }

        public Criteria andLastUpdLessThan(Date value) {
            addCriterionForJDBCDate("LAST_UPD <", value, "lastUpd");
            return (Criteria) this;
        }

        public Criteria andLastUpdLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LAST_UPD <=", value, "lastUpd");
            return (Criteria) this;
        }

        public Criteria andLastUpdIn(List<Date> values) {
            addCriterionForJDBCDate("LAST_UPD in", values, "lastUpd");
            return (Criteria) this;
        }

        public Criteria andLastUpdNotIn(List<Date> values) {
            addCriterionForJDBCDate("LAST_UPD not in", values, "lastUpd");
            return (Criteria) this;
        }

        public Criteria andLastUpdBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LAST_UPD between", value1, value2, "lastUpd");
            return (Criteria) this;
        }

        public Criteria andLastUpdNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LAST_UPD not between", value1, value2, "lastUpd");
            return (Criteria) this;
        }

        public Criteria andLastUpdByIsNull() {
            addCriterion("LAST_UPD_BY is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdByIsNotNull() {
            addCriterion("LAST_UPD_BY is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdByEqualTo(String value) {
            addCriterion("LAST_UPD_BY =", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotEqualTo(String value) {
            addCriterion("LAST_UPD_BY <>", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByGreaterThan(String value) {
            addCriterion("LAST_UPD_BY >", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_UPD_BY >=", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByLessThan(String value) {
            addCriterion("LAST_UPD_BY <", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByLessThanOrEqualTo(String value) {
            addCriterion("LAST_UPD_BY <=", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByLike(String value) {
            addCriterion("LAST_UPD_BY like", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotLike(String value) {
            addCriterion("LAST_UPD_BY not like", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByIn(List<String> values) {
            addCriterion("LAST_UPD_BY in", values, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotIn(List<String> values) {
            addCriterion("LAST_UPD_BY not in", values, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByBetween(String value1, String value2) {
            addCriterion("LAST_UPD_BY between", value1, value2, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotBetween(String value1, String value2) {
            addCriterion("LAST_UPD_BY not between", value1, value2, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andModificationNumIsNull() {
            addCriterion("MODIFICATION_NUM is null");
            return (Criteria) this;
        }

        public Criteria andModificationNumIsNotNull() {
            addCriterion("MODIFICATION_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andModificationNumEqualTo(Long value) {
            addCriterion("MODIFICATION_NUM =", value, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumNotEqualTo(Long value) {
            addCriterion("MODIFICATION_NUM <>", value, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumGreaterThan(Long value) {
            addCriterion("MODIFICATION_NUM >", value, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumGreaterThanOrEqualTo(Long value) {
            addCriterion("MODIFICATION_NUM >=", value, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumLessThan(Long value) {
            addCriterion("MODIFICATION_NUM <", value, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumLessThanOrEqualTo(Long value) {
            addCriterion("MODIFICATION_NUM <=", value, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumIn(List<Long> values) {
            addCriterion("MODIFICATION_NUM in", values, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumNotIn(List<Long> values) {
            addCriterion("MODIFICATION_NUM not in", values, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumBetween(Long value1, Long value2) {
            addCriterion("MODIFICATION_NUM between", value1, value2, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumNotBetween(Long value1, Long value2) {
            addCriterion("MODIFICATION_NUM not between", value1, value2, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andConflictIdIsNull() {
            addCriterion("CONFLICT_ID is null");
            return (Criteria) this;
        }

        public Criteria andConflictIdIsNotNull() {
            addCriterion("CONFLICT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andConflictIdEqualTo(String value) {
            addCriterion("CONFLICT_ID =", value, "conflictId");
            return (Criteria) this;
        }

        public Criteria andConflictIdNotEqualTo(String value) {
            addCriterion("CONFLICT_ID <>", value, "conflictId");
            return (Criteria) this;
        }

        public Criteria andConflictIdGreaterThan(String value) {
            addCriterion("CONFLICT_ID >", value, "conflictId");
            return (Criteria) this;
        }

        public Criteria andConflictIdGreaterThanOrEqualTo(String value) {
            addCriterion("CONFLICT_ID >=", value, "conflictId");
            return (Criteria) this;
        }

        public Criteria andConflictIdLessThan(String value) {
            addCriterion("CONFLICT_ID <", value, "conflictId");
            return (Criteria) this;
        }

        public Criteria andConflictIdLessThanOrEqualTo(String value) {
            addCriterion("CONFLICT_ID <=", value, "conflictId");
            return (Criteria) this;
        }

        public Criteria andConflictIdLike(String value) {
            addCriterion("CONFLICT_ID like", value, "conflictId");
            return (Criteria) this;
        }

        public Criteria andConflictIdNotLike(String value) {
            addCriterion("CONFLICT_ID not like", value, "conflictId");
            return (Criteria) this;
        }

        public Criteria andConflictIdIn(List<String> values) {
            addCriterion("CONFLICT_ID in", values, "conflictId");
            return (Criteria) this;
        }

        public Criteria andConflictIdNotIn(List<String> values) {
            addCriterion("CONFLICT_ID not in", values, "conflictId");
            return (Criteria) this;
        }

        public Criteria andConflictIdBetween(String value1, String value2) {
            addCriterion("CONFLICT_ID between", value1, value2, "conflictId");
            return (Criteria) this;
        }

        public Criteria andConflictIdNotBetween(String value1, String value2) {
            addCriterion("CONFLICT_ID not between", value1, value2, "conflictId");
            return (Criteria) this;
        }

        public Criteria andActlEndDtIsNull() {
            addCriterion("ACTL_END_DT is null");
            return (Criteria) this;
        }

        public Criteria andActlEndDtIsNotNull() {
            addCriterion("ACTL_END_DT is not null");
            return (Criteria) this;
        }

        public Criteria andActlEndDtEqualTo(Date value) {
            addCriterionForJDBCDate("ACTL_END_DT =", value, "actlEndDt");
            return (Criteria) this;
        }

        public Criteria andActlEndDtNotEqualTo(Date value) {
            addCriterionForJDBCDate("ACTL_END_DT <>", value, "actlEndDt");
            return (Criteria) this;
        }

        public Criteria andActlEndDtGreaterThan(Date value) {
            addCriterionForJDBCDate("ACTL_END_DT >", value, "actlEndDt");
            return (Criteria) this;
        }

        public Criteria andActlEndDtGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ACTL_END_DT >=", value, "actlEndDt");
            return (Criteria) this;
        }

        public Criteria andActlEndDtLessThan(Date value) {
            addCriterionForJDBCDate("ACTL_END_DT <", value, "actlEndDt");
            return (Criteria) this;
        }

        public Criteria andActlEndDtLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ACTL_END_DT <=", value, "actlEndDt");
            return (Criteria) this;
        }

        public Criteria andActlEndDtIn(List<Date> values) {
            addCriterionForJDBCDate("ACTL_END_DT in", values, "actlEndDt");
            return (Criteria) this;
        }

        public Criteria andActlEndDtNotIn(List<Date> values) {
            addCriterionForJDBCDate("ACTL_END_DT not in", values, "actlEndDt");
            return (Criteria) this;
        }

        public Criteria andActlEndDtBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ACTL_END_DT between", value1, value2, "actlEndDt");
            return (Criteria) this;
        }

        public Criteria andActlEndDtNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ACTL_END_DT not between", value1, value2, "actlEndDt");
            return (Criteria) this;
        }

        public Criteria andActlStartDtIsNull() {
            addCriterion("ACTL_START_DT is null");
            return (Criteria) this;
        }

        public Criteria andActlStartDtIsNotNull() {
            addCriterion("ACTL_START_DT is not null");
            return (Criteria) this;
        }

        public Criteria andActlStartDtEqualTo(Date value) {
            addCriterionForJDBCDate("ACTL_START_DT =", value, "actlStartDt");
            return (Criteria) this;
        }

        public Criteria andActlStartDtNotEqualTo(Date value) {
            addCriterionForJDBCDate("ACTL_START_DT <>", value, "actlStartDt");
            return (Criteria) this;
        }

        public Criteria andActlStartDtGreaterThan(Date value) {
            addCriterionForJDBCDate("ACTL_START_DT >", value, "actlStartDt");
            return (Criteria) this;
        }

        public Criteria andActlStartDtGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ACTL_START_DT >=", value, "actlStartDt");
            return (Criteria) this;
        }

        public Criteria andActlStartDtLessThan(Date value) {
            addCriterionForJDBCDate("ACTL_START_DT <", value, "actlStartDt");
            return (Criteria) this;
        }

        public Criteria andActlStartDtLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ACTL_START_DT <=", value, "actlStartDt");
            return (Criteria) this;
        }

        public Criteria andActlStartDtIn(List<Date> values) {
            addCriterionForJDBCDate("ACTL_START_DT in", values, "actlStartDt");
            return (Criteria) this;
        }

        public Criteria andActlStartDtNotIn(List<Date> values) {
            addCriterionForJDBCDate("ACTL_START_DT not in", values, "actlStartDt");
            return (Criteria) this;
        }

        public Criteria andActlStartDtBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ACTL_START_DT between", value1, value2, "actlStartDt");
            return (Criteria) this;
        }

        public Criteria andActlStartDtNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ACTL_START_DT not between", value1, value2, "actlStartDt");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdIsNull() {
            addCriterion("DB_LAST_UPD is null");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdIsNotNull() {
            addCriterion("DB_LAST_UPD is not null");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdEqualTo(Date value) {
            addCriterionForJDBCDate("DB_LAST_UPD =", value, "dbLastUpd");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdNotEqualTo(Date value) {
            addCriterionForJDBCDate("DB_LAST_UPD <>", value, "dbLastUpd");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdGreaterThan(Date value) {
            addCriterionForJDBCDate("DB_LAST_UPD >", value, "dbLastUpd");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("DB_LAST_UPD >=", value, "dbLastUpd");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdLessThan(Date value) {
            addCriterionForJDBCDate("DB_LAST_UPD <", value, "dbLastUpd");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("DB_LAST_UPD <=", value, "dbLastUpd");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdIn(List<Date> values) {
            addCriterionForJDBCDate("DB_LAST_UPD in", values, "dbLastUpd");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdNotIn(List<Date> values) {
            addCriterionForJDBCDate("DB_LAST_UPD not in", values, "dbLastUpd");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("DB_LAST_UPD between", value1, value2, "dbLastUpd");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("DB_LAST_UPD not between", value1, value2, "dbLastUpd");
            return (Criteria) this;
        }

        public Criteria andExpirationDtIsNull() {
            addCriterion("EXPIRATION_DT is null");
            return (Criteria) this;
        }

        public Criteria andExpirationDtIsNotNull() {
            addCriterion("EXPIRATION_DT is not null");
            return (Criteria) this;
        }

        public Criteria andExpirationDtEqualTo(Date value) {
            addCriterionForJDBCDate("EXPIRATION_DT =", value, "expirationDt");
            return (Criteria) this;
        }

        public Criteria andExpirationDtNotEqualTo(Date value) {
            addCriterionForJDBCDate("EXPIRATION_DT <>", value, "expirationDt");
            return (Criteria) this;
        }

        public Criteria andExpirationDtGreaterThan(Date value) {
            addCriterionForJDBCDate("EXPIRATION_DT >", value, "expirationDt");
            return (Criteria) this;
        }

        public Criteria andExpirationDtGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EXPIRATION_DT >=", value, "expirationDt");
            return (Criteria) this;
        }

        public Criteria andExpirationDtLessThan(Date value) {
            addCriterionForJDBCDate("EXPIRATION_DT <", value, "expirationDt");
            return (Criteria) this;
        }

        public Criteria andExpirationDtLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("EXPIRATION_DT <=", value, "expirationDt");
            return (Criteria) this;
        }

        public Criteria andExpirationDtIn(List<Date> values) {
            addCriterionForJDBCDate("EXPIRATION_DT in", values, "expirationDt");
            return (Criteria) this;
        }

        public Criteria andExpirationDtNotIn(List<Date> values) {
            addCriterionForJDBCDate("EXPIRATION_DT not in", values, "expirationDt");
            return (Criteria) this;
        }

        public Criteria andExpirationDtBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EXPIRATION_DT between", value1, value2, "expirationDt");
            return (Criteria) this;
        }

        public Criteria andExpirationDtNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("EXPIRATION_DT not between", value1, value2, "expirationDt");
            return (Criteria) this;
        }

        public Criteria andSchedStartDtIsNull() {
            addCriterion("SCHED_START_DT is null");
            return (Criteria) this;
        }

        public Criteria andSchedStartDtIsNotNull() {
            addCriterion("SCHED_START_DT is not null");
            return (Criteria) this;
        }

        public Criteria andSchedStartDtEqualTo(Date value) {
            addCriterionForJDBCDate("SCHED_START_DT =", value, "schedStartDt");
            return (Criteria) this;
        }

        public Criteria andSchedStartDtNotEqualTo(Date value) {
            addCriterionForJDBCDate("SCHED_START_DT <>", value, "schedStartDt");
            return (Criteria) this;
        }

        public Criteria andSchedStartDtGreaterThan(Date value) {
            addCriterionForJDBCDate("SCHED_START_DT >", value, "schedStartDt");
            return (Criteria) this;
        }

        public Criteria andSchedStartDtGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SCHED_START_DT >=", value, "schedStartDt");
            return (Criteria) this;
        }

        public Criteria andSchedStartDtLessThan(Date value) {
            addCriterionForJDBCDate("SCHED_START_DT <", value, "schedStartDt");
            return (Criteria) this;
        }

        public Criteria andSchedStartDtLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SCHED_START_DT <=", value, "schedStartDt");
            return (Criteria) this;
        }

        public Criteria andSchedStartDtIn(List<Date> values) {
            addCriterionForJDBCDate("SCHED_START_DT in", values, "schedStartDt");
            return (Criteria) this;
        }

        public Criteria andSchedStartDtNotIn(List<Date> values) {
            addCriterionForJDBCDate("SCHED_START_DT not in", values, "schedStartDt");
            return (Criteria) this;
        }

        public Criteria andSchedStartDtBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SCHED_START_DT between", value1, value2, "schedStartDt");
            return (Criteria) this;
        }

        public Criteria andSchedStartDtNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SCHED_START_DT not between", value1, value2, "schedStartDt");
            return (Criteria) this;
        }

        public Criteria andSubmitDateIsNull() {
            addCriterion("SUBMIT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSubmitDateIsNotNull() {
            addCriterion("SUBMIT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSubmitDateEqualTo(Date value) {
            addCriterionForJDBCDate("SUBMIT_DATE =", value, "submitDate");
            return (Criteria) this;
        }

        public Criteria andSubmitDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("SUBMIT_DATE <>", value, "submitDate");
            return (Criteria) this;
        }

        public Criteria andSubmitDateGreaterThan(Date value) {
            addCriterionForJDBCDate("SUBMIT_DATE >", value, "submitDate");
            return (Criteria) this;
        }

        public Criteria andSubmitDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SUBMIT_DATE >=", value, "submitDate");
            return (Criteria) this;
        }

        public Criteria andSubmitDateLessThan(Date value) {
            addCriterionForJDBCDate("SUBMIT_DATE <", value, "submitDate");
            return (Criteria) this;
        }

        public Criteria andSubmitDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SUBMIT_DATE <=", value, "submitDate");
            return (Criteria) this;
        }

        public Criteria andSubmitDateIn(List<Date> values) {
            addCriterionForJDBCDate("SUBMIT_DATE in", values, "submitDate");
            return (Criteria) this;
        }

        public Criteria andSubmitDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("SUBMIT_DATE not in", values, "submitDate");
            return (Criteria) this;
        }

        public Criteria andSubmitDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SUBMIT_DATE between", value1, value2, "submitDate");
            return (Criteria) this;
        }

        public Criteria andSubmitDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SUBMIT_DATE not between", value1, value2, "submitDate");
            return (Criteria) this;
        }

        public Criteria andClassNameIsNull() {
            addCriterion("CLASS_NAME is null");
            return (Criteria) this;
        }

        public Criteria andClassNameIsNotNull() {
            addCriterion("CLASS_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andClassNameEqualTo(String value) {
            addCriterion("CLASS_NAME =", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotEqualTo(String value) {
            addCriterion("CLASS_NAME <>", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameGreaterThan(String value) {
            addCriterion("CLASS_NAME >", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameGreaterThanOrEqualTo(String value) {
            addCriterion("CLASS_NAME >=", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLessThan(String value) {
            addCriterion("CLASS_NAME <", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLessThanOrEqualTo(String value) {
            addCriterion("CLASS_NAME <=", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameLike(String value) {
            addCriterion("CLASS_NAME like", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotLike(String value) {
            addCriterion("CLASS_NAME not like", value, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameIn(List<String> values) {
            addCriterion("CLASS_NAME in", values, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotIn(List<String> values) {
            addCriterion("CLASS_NAME not in", values, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameBetween(String value1, String value2) {
            addCriterion("CLASS_NAME between", value1, value2, "className");
            return (Criteria) this;
        }

        public Criteria andClassNameNotBetween(String value1, String value2) {
            addCriterion("CLASS_NAME not between", value1, value2, "className");
            return (Criteria) this;
        }

        public Criteria andCompletionCdIsNull() {
            addCriterion("COMPLETION_CD is null");
            return (Criteria) this;
        }

        public Criteria andCompletionCdIsNotNull() {
            addCriterion("COMPLETION_CD is not null");
            return (Criteria) this;
        }

        public Criteria andCompletionCdEqualTo(String value) {
            addCriterion("COMPLETION_CD =", value, "completionCd");
            return (Criteria) this;
        }

        public Criteria andCompletionCdNotEqualTo(String value) {
            addCriterion("COMPLETION_CD <>", value, "completionCd");
            return (Criteria) this;
        }

        public Criteria andCompletionCdGreaterThan(String value) {
            addCriterion("COMPLETION_CD >", value, "completionCd");
            return (Criteria) this;
        }

        public Criteria andCompletionCdGreaterThanOrEqualTo(String value) {
            addCriterion("COMPLETION_CD >=", value, "completionCd");
            return (Criteria) this;
        }

        public Criteria andCompletionCdLessThan(String value) {
            addCriterion("COMPLETION_CD <", value, "completionCd");
            return (Criteria) this;
        }

        public Criteria andCompletionCdLessThanOrEqualTo(String value) {
            addCriterion("COMPLETION_CD <=", value, "completionCd");
            return (Criteria) this;
        }

        public Criteria andCompletionCdLike(String value) {
            addCriterion("COMPLETION_CD like", value, "completionCd");
            return (Criteria) this;
        }

        public Criteria andCompletionCdNotLike(String value) {
            addCriterion("COMPLETION_CD not like", value, "completionCd");
            return (Criteria) this;
        }

        public Criteria andCompletionCdIn(List<String> values) {
            addCriterion("COMPLETION_CD in", values, "completionCd");
            return (Criteria) this;
        }

        public Criteria andCompletionCdNotIn(List<String> values) {
            addCriterion("COMPLETION_CD not in", values, "completionCd");
            return (Criteria) this;
        }

        public Criteria andCompletionCdBetween(String value1, String value2) {
            addCriterion("COMPLETION_CD between", value1, value2, "completionCd");
            return (Criteria) this;
        }

        public Criteria andCompletionCdNotBetween(String value1, String value2) {
            addCriterion("COMPLETION_CD not between", value1, value2, "completionCd");
            return (Criteria) this;
        }

        public Criteria andCompletionTextIsNull() {
            addCriterion("COMPLETION_TEXT is null");
            return (Criteria) this;
        }

        public Criteria andCompletionTextIsNotNull() {
            addCriterion("COMPLETION_TEXT is not null");
            return (Criteria) this;
        }

        public Criteria andCompletionTextEqualTo(String value) {
            addCriterion("COMPLETION_TEXT =", value, "completionText");
            return (Criteria) this;
        }

        public Criteria andCompletionTextNotEqualTo(String value) {
            addCriterion("COMPLETION_TEXT <>", value, "completionText");
            return (Criteria) this;
        }

        public Criteria andCompletionTextGreaterThan(String value) {
            addCriterion("COMPLETION_TEXT >", value, "completionText");
            return (Criteria) this;
        }

        public Criteria andCompletionTextGreaterThanOrEqualTo(String value) {
            addCriterion("COMPLETION_TEXT >=", value, "completionText");
            return (Criteria) this;
        }

        public Criteria andCompletionTextLessThan(String value) {
            addCriterion("COMPLETION_TEXT <", value, "completionText");
            return (Criteria) this;
        }

        public Criteria andCompletionTextLessThanOrEqualTo(String value) {
            addCriterion("COMPLETION_TEXT <=", value, "completionText");
            return (Criteria) this;
        }

        public Criteria andCompletionTextLike(String value) {
            addCriterion("COMPLETION_TEXT like", value, "completionText");
            return (Criteria) this;
        }

        public Criteria andCompletionTextNotLike(String value) {
            addCriterion("COMPLETION_TEXT not like", value, "completionText");
            return (Criteria) this;
        }

        public Criteria andCompletionTextIn(List<String> values) {
            addCriterion("COMPLETION_TEXT in", values, "completionText");
            return (Criteria) this;
        }

        public Criteria andCompletionTextNotIn(List<String> values) {
            addCriterion("COMPLETION_TEXT not in", values, "completionText");
            return (Criteria) this;
        }

        public Criteria andCompletionTextBetween(String value1, String value2) {
            addCriterion("COMPLETION_TEXT between", value1, value2, "completionText");
            return (Criteria) this;
        }

        public Criteria andCompletionTextNotBetween(String value1, String value2) {
            addCriterion("COMPLETION_TEXT not between", value1, value2, "completionText");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdSrcIsNull() {
            addCriterion("DB_LAST_UPD_SRC is null");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdSrcIsNotNull() {
            addCriterion("DB_LAST_UPD_SRC is not null");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdSrcEqualTo(String value) {
            addCriterion("DB_LAST_UPD_SRC =", value, "dbLastUpdSrc");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdSrcNotEqualTo(String value) {
            addCriterion("DB_LAST_UPD_SRC <>", value, "dbLastUpdSrc");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdSrcGreaterThan(String value) {
            addCriterion("DB_LAST_UPD_SRC >", value, "dbLastUpdSrc");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdSrcGreaterThanOrEqualTo(String value) {
            addCriterion("DB_LAST_UPD_SRC >=", value, "dbLastUpdSrc");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdSrcLessThan(String value) {
            addCriterion("DB_LAST_UPD_SRC <", value, "dbLastUpdSrc");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdSrcLessThanOrEqualTo(String value) {
            addCriterion("DB_LAST_UPD_SRC <=", value, "dbLastUpdSrc");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdSrcLike(String value) {
            addCriterion("DB_LAST_UPD_SRC like", value, "dbLastUpdSrc");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdSrcNotLike(String value) {
            addCriterion("DB_LAST_UPD_SRC not like", value, "dbLastUpdSrc");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdSrcIn(List<String> values) {
            addCriterion("DB_LAST_UPD_SRC in", values, "dbLastUpdSrc");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdSrcNotIn(List<String> values) {
            addCriterion("DB_LAST_UPD_SRC not in", values, "dbLastUpdSrc");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdSrcBetween(String value1, String value2) {
            addCriterion("DB_LAST_UPD_SRC between", value1, value2, "dbLastUpdSrc");
            return (Criteria) this;
        }

        public Criteria andDbLastUpdSrcNotBetween(String value1, String value2) {
            addCriterion("DB_LAST_UPD_SRC not between", value1, value2, "dbLastUpdSrc");
            return (Criteria) this;
        }

        public Criteria andDescTextIsNull() {
            addCriterion("DESC_TEXT is null");
            return (Criteria) this;
        }

        public Criteria andDescTextIsNotNull() {
            addCriterion("DESC_TEXT is not null");
            return (Criteria) this;
        }

        public Criteria andDescTextEqualTo(String value) {
            addCriterion("DESC_TEXT =", value, "descText");
            return (Criteria) this;
        }

        public Criteria andDescTextNotEqualTo(String value) {
            addCriterion("DESC_TEXT <>", value, "descText");
            return (Criteria) this;
        }

        public Criteria andDescTextGreaterThan(String value) {
            addCriterion("DESC_TEXT >", value, "descText");
            return (Criteria) this;
        }

        public Criteria andDescTextGreaterThanOrEqualTo(String value) {
            addCriterion("DESC_TEXT >=", value, "descText");
            return (Criteria) this;
        }

        public Criteria andDescTextLessThan(String value) {
            addCriterion("DESC_TEXT <", value, "descText");
            return (Criteria) this;
        }

        public Criteria andDescTextLessThanOrEqualTo(String value) {
            addCriterion("DESC_TEXT <=", value, "descText");
            return (Criteria) this;
        }

        public Criteria andDescTextLike(String value) {
            addCriterion("DESC_TEXT like", value, "descText");
            return (Criteria) this;
        }

        public Criteria andDescTextNotLike(String value) {
            addCriterion("DESC_TEXT not like", value, "descText");
            return (Criteria) this;
        }

        public Criteria andDescTextIn(List<String> values) {
            addCriterion("DESC_TEXT in", values, "descText");
            return (Criteria) this;
        }

        public Criteria andDescTextNotIn(List<String> values) {
            addCriterion("DESC_TEXT not in", values, "descText");
            return (Criteria) this;
        }

        public Criteria andDescTextBetween(String value1, String value2) {
            addCriterion("DESC_TEXT between", value1, value2, "descText");
            return (Criteria) this;
        }

        public Criteria andDescTextNotBetween(String value1, String value2) {
            addCriterion("DESC_TEXT not between", value1, value2, "descText");
            return (Criteria) this;
        }

        public Criteria andExecSrvrNameIsNull() {
            addCriterion("EXEC_SRVR_NAME is null");
            return (Criteria) this;
        }

        public Criteria andExecSrvrNameIsNotNull() {
            addCriterion("EXEC_SRVR_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andExecSrvrNameEqualTo(String value) {
            addCriterion("EXEC_SRVR_NAME =", value, "execSrvrName");
            return (Criteria) this;
        }

        public Criteria andExecSrvrNameNotEqualTo(String value) {
            addCriterion("EXEC_SRVR_NAME <>", value, "execSrvrName");
            return (Criteria) this;
        }

        public Criteria andExecSrvrNameGreaterThan(String value) {
            addCriterion("EXEC_SRVR_NAME >", value, "execSrvrName");
            return (Criteria) this;
        }

        public Criteria andExecSrvrNameGreaterThanOrEqualTo(String value) {
            addCriterion("EXEC_SRVR_NAME >=", value, "execSrvrName");
            return (Criteria) this;
        }

        public Criteria andExecSrvrNameLessThan(String value) {
            addCriterion("EXEC_SRVR_NAME <", value, "execSrvrName");
            return (Criteria) this;
        }

        public Criteria andExecSrvrNameLessThanOrEqualTo(String value) {
            addCriterion("EXEC_SRVR_NAME <=", value, "execSrvrName");
            return (Criteria) this;
        }

        public Criteria andExecSrvrNameLike(String value) {
            addCriterion("EXEC_SRVR_NAME like", value, "execSrvrName");
            return (Criteria) this;
        }

        public Criteria andExecSrvrNameNotLike(String value) {
            addCriterion("EXEC_SRVR_NAME not like", value, "execSrvrName");
            return (Criteria) this;
        }

        public Criteria andExecSrvrNameIn(List<String> values) {
            addCriterion("EXEC_SRVR_NAME in", values, "execSrvrName");
            return (Criteria) this;
        }

        public Criteria andExecSrvrNameNotIn(List<String> values) {
            addCriterion("EXEC_SRVR_NAME not in", values, "execSrvrName");
            return (Criteria) this;
        }

        public Criteria andExecSrvrNameBetween(String value1, String value2) {
            addCriterion("EXEC_SRVR_NAME between", value1, value2, "execSrvrName");
            return (Criteria) this;
        }

        public Criteria andExecSrvrNameNotBetween(String value1, String value2) {
            addCriterion("EXEC_SRVR_NAME not between", value1, value2, "execSrvrName");
            return (Criteria) this;
        }

        public Criteria andMethodIsNull() {
            addCriterion("METHOD is null");
            return (Criteria) this;
        }

        public Criteria andMethodIsNotNull() {
            addCriterion("METHOD is not null");
            return (Criteria) this;
        }

        public Criteria andMethodEqualTo(String value) {
            addCriterion("METHOD =", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotEqualTo(String value) {
            addCriterion("METHOD <>", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodGreaterThan(String value) {
            addCriterion("METHOD >", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodGreaterThanOrEqualTo(String value) {
            addCriterion("METHOD >=", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodLessThan(String value) {
            addCriterion("METHOD <", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodLessThanOrEqualTo(String value) {
            addCriterion("METHOD <=", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodLike(String value) {
            addCriterion("METHOD like", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotLike(String value) {
            addCriterion("METHOD not like", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodIn(List<String> values) {
            addCriterion("METHOD in", values, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotIn(List<String> values) {
            addCriterion("METHOD not in", values, "method");
            return (Criteria) this;
        }

        public Criteria andMethodBetween(String value1, String value2) {
            addCriterion("METHOD between", value1, value2, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotBetween(String value1, String value2) {
            addCriterion("METHOD not between", value1, value2, "method");
            return (Criteria) this;
        }

        public Criteria andTmodelIsNull() {
            addCriterion("TMODEL is null");
            return (Criteria) this;
        }

        public Criteria andTmodelIsNotNull() {
            addCriterion("TMODEL is not null");
            return (Criteria) this;
        }

        public Criteria andTmodelEqualTo(String value) {
            addCriterion("TMODEL =", value, "tmodel");
            return (Criteria) this;
        }

        public Criteria andTmodelNotEqualTo(String value) {
            addCriterion("TMODEL <>", value, "tmodel");
            return (Criteria) this;
        }

        public Criteria andTmodelGreaterThan(String value) {
            addCriterion("TMODEL >", value, "tmodel");
            return (Criteria) this;
        }

        public Criteria andTmodelGreaterThanOrEqualTo(String value) {
            addCriterion("TMODEL >=", value, "tmodel");
            return (Criteria) this;
        }

        public Criteria andTmodelLessThan(String value) {
            addCriterion("TMODEL <", value, "tmodel");
            return (Criteria) this;
        }

        public Criteria andTmodelLessThanOrEqualTo(String value) {
            addCriterion("TMODEL <=", value, "tmodel");
            return (Criteria) this;
        }

        public Criteria andTmodelLike(String value) {
            addCriterion("TMODEL like", value, "tmodel");
            return (Criteria) this;
        }

        public Criteria andTmodelNotLike(String value) {
            addCriterion("TMODEL not like", value, "tmodel");
            return (Criteria) this;
        }

        public Criteria andTmodelIn(List<String> values) {
            addCriterion("TMODEL in", values, "tmodel");
            return (Criteria) this;
        }

        public Criteria andTmodelNotIn(List<String> values) {
            addCriterion("TMODEL not in", values, "tmodel");
            return (Criteria) this;
        }

        public Criteria andTmodelBetween(String value1, String value2) {
            addCriterion("TMODEL between", value1, value2, "tmodel");
            return (Criteria) this;
        }

        public Criteria andTmodelNotBetween(String value1, String value2) {
            addCriterion("TMODEL not between", value1, value2, "tmodel");
            return (Criteria) this;
        }

        public Criteria andRptFlagIsNull() {
            addCriterion("RPT_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andRptFlagIsNotNull() {
            addCriterion("RPT_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andRptFlagEqualTo(String value) {
            addCriterion("RPT_FLAG =", value, "rptFlag");
            return (Criteria) this;
        }

        public Criteria andRptFlagNotEqualTo(String value) {
            addCriterion("RPT_FLAG <>", value, "rptFlag");
            return (Criteria) this;
        }

        public Criteria andRptFlagGreaterThan(String value) {
            addCriterion("RPT_FLAG >", value, "rptFlag");
            return (Criteria) this;
        }

        public Criteria andRptFlagGreaterThanOrEqualTo(String value) {
            addCriterion("RPT_FLAG >=", value, "rptFlag");
            return (Criteria) this;
        }

        public Criteria andRptFlagLessThan(String value) {
            addCriterion("RPT_FLAG <", value, "rptFlag");
            return (Criteria) this;
        }

        public Criteria andRptFlagLessThanOrEqualTo(String value) {
            addCriterion("RPT_FLAG <=", value, "rptFlag");
            return (Criteria) this;
        }

        public Criteria andRptFlagLike(String value) {
            addCriterion("RPT_FLAG like", value, "rptFlag");
            return (Criteria) this;
        }

        public Criteria andRptFlagNotLike(String value) {
            addCriterion("RPT_FLAG not like", value, "rptFlag");
            return (Criteria) this;
        }

        public Criteria andRptFlagIn(List<String> values) {
            addCriterion("RPT_FLAG in", values, "rptFlag");
            return (Criteria) this;
        }

        public Criteria andRptFlagNotIn(List<String> values) {
            addCriterion("RPT_FLAG not in", values, "rptFlag");
            return (Criteria) this;
        }

        public Criteria andRptFlagBetween(String value1, String value2) {
            addCriterion("RPT_FLAG between", value1, value2, "rptFlag");
            return (Criteria) this;
        }

        public Criteria andRptFlagNotBetween(String value1, String value2) {
            addCriterion("RPT_FLAG not between", value1, value2, "rptFlag");
            return (Criteria) this;
        }

        public Criteria andRptIntervalIsNull() {
            addCriterion("RPT_INTERVAL is null");
            return (Criteria) this;
        }

        public Criteria andRptIntervalIsNotNull() {
            addCriterion("RPT_INTERVAL is not null");
            return (Criteria) this;
        }

        public Criteria andRptIntervalEqualTo(String value) {
            addCriterion("RPT_INTERVAL =", value, "rptInterval");
            return (Criteria) this;
        }

        public Criteria andRptIntervalNotEqualTo(String value) {
            addCriterion("RPT_INTERVAL <>", value, "rptInterval");
            return (Criteria) this;
        }

        public Criteria andRptIntervalGreaterThan(String value) {
            addCriterion("RPT_INTERVAL >", value, "rptInterval");
            return (Criteria) this;
        }

        public Criteria andRptIntervalGreaterThanOrEqualTo(String value) {
            addCriterion("RPT_INTERVAL >=", value, "rptInterval");
            return (Criteria) this;
        }

        public Criteria andRptIntervalLessThan(String value) {
            addCriterion("RPT_INTERVAL <", value, "rptInterval");
            return (Criteria) this;
        }

        public Criteria andRptIntervalLessThanOrEqualTo(String value) {
            addCriterion("RPT_INTERVAL <=", value, "rptInterval");
            return (Criteria) this;
        }

        public Criteria andRptIntervalLike(String value) {
            addCriterion("RPT_INTERVAL like", value, "rptInterval");
            return (Criteria) this;
        }

        public Criteria andRptIntervalNotLike(String value) {
            addCriterion("RPT_INTERVAL not like", value, "rptInterval");
            return (Criteria) this;
        }

        public Criteria andRptIntervalIn(List<String> values) {
            addCriterion("RPT_INTERVAL in", values, "rptInterval");
            return (Criteria) this;
        }

        public Criteria andRptIntervalNotIn(List<String> values) {
            addCriterion("RPT_INTERVAL not in", values, "rptInterval");
            return (Criteria) this;
        }

        public Criteria andRptIntervalBetween(String value1, String value2) {
            addCriterion("RPT_INTERVAL between", value1, value2, "rptInterval");
            return (Criteria) this;
        }

        public Criteria andRptIntervalNotBetween(String value1, String value2) {
            addCriterion("RPT_INTERVAL not between", value1, value2, "rptInterval");
            return (Criteria) this;
        }

        public Criteria andRptUomIsNull() {
            addCriterion("RPT_UOM is null");
            return (Criteria) this;
        }

        public Criteria andRptUomIsNotNull() {
            addCriterion("RPT_UOM is not null");
            return (Criteria) this;
        }

        public Criteria andRptUomEqualTo(String value) {
            addCriterion("RPT_UOM =", value, "rptUom");
            return (Criteria) this;
        }

        public Criteria andRptUomNotEqualTo(String value) {
            addCriterion("RPT_UOM <>", value, "rptUom");
            return (Criteria) this;
        }

        public Criteria andRptUomGreaterThan(String value) {
            addCriterion("RPT_UOM >", value, "rptUom");
            return (Criteria) this;
        }

        public Criteria andRptUomGreaterThanOrEqualTo(String value) {
            addCriterion("RPT_UOM >=", value, "rptUom");
            return (Criteria) this;
        }

        public Criteria andRptUomLessThan(String value) {
            addCriterion("RPT_UOM <", value, "rptUom");
            return (Criteria) this;
        }

        public Criteria andRptUomLessThanOrEqualTo(String value) {
            addCriterion("RPT_UOM <=", value, "rptUom");
            return (Criteria) this;
        }

        public Criteria andRptUomLike(String value) {
            addCriterion("RPT_UOM like", value, "rptUom");
            return (Criteria) this;
        }

        public Criteria andRptUomNotLike(String value) {
            addCriterion("RPT_UOM not like", value, "rptUom");
            return (Criteria) this;
        }

        public Criteria andRptUomIn(List<String> values) {
            addCriterion("RPT_UOM in", values, "rptUom");
            return (Criteria) this;
        }

        public Criteria andRptUomNotIn(List<String> values) {
            addCriterion("RPT_UOM not in", values, "rptUom");
            return (Criteria) this;
        }

        public Criteria andRptUomBetween(String value1, String value2) {
            addCriterion("RPT_UOM between", value1, value2, "rptUom");
            return (Criteria) this;
        }

        public Criteria andRptUomNotBetween(String value1, String value2) {
            addCriterion("RPT_UOM not between", value1, value2, "rptUom");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andTaskPidIsNull() {
            addCriterion("TASK_PID is null");
            return (Criteria) this;
        }

        public Criteria andTaskPidIsNotNull() {
            addCriterion("TASK_PID is not null");
            return (Criteria) this;
        }

        public Criteria andTaskPidEqualTo(String value) {
            addCriterion("TASK_PID =", value, "taskPid");
            return (Criteria) this;
        }

        public Criteria andTaskPidNotEqualTo(String value) {
            addCriterion("TASK_PID <>", value, "taskPid");
            return (Criteria) this;
        }

        public Criteria andTaskPidGreaterThan(String value) {
            addCriterion("TASK_PID >", value, "taskPid");
            return (Criteria) this;
        }

        public Criteria andTaskPidGreaterThanOrEqualTo(String value) {
            addCriterion("TASK_PID >=", value, "taskPid");
            return (Criteria) this;
        }

        public Criteria andTaskPidLessThan(String value) {
            addCriterion("TASK_PID <", value, "taskPid");
            return (Criteria) this;
        }

        public Criteria andTaskPidLessThanOrEqualTo(String value) {
            addCriterion("TASK_PID <=", value, "taskPid");
            return (Criteria) this;
        }

        public Criteria andTaskPidLike(String value) {
            addCriterion("TASK_PID like", value, "taskPid");
            return (Criteria) this;
        }

        public Criteria andTaskPidNotLike(String value) {
            addCriterion("TASK_PID not like", value, "taskPid");
            return (Criteria) this;
        }

        public Criteria andTaskPidIn(List<String> values) {
            addCriterion("TASK_PID in", values, "taskPid");
            return (Criteria) this;
        }

        public Criteria andTaskPidNotIn(List<String> values) {
            addCriterion("TASK_PID not in", values, "taskPid");
            return (Criteria) this;
        }

        public Criteria andTaskPidBetween(String value1, String value2) {
            addCriterion("TASK_PID between", value1, value2, "taskPid");
            return (Criteria) this;
        }

        public Criteria andTaskPidNotBetween(String value1, String value2) {
            addCriterion("TASK_PID not between", value1, value2, "taskPid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SIEBEL.CX_THREAD_REQ
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SIEBEL.CX_THREAD_REQ
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}