package com.zte.mcrm.system.access.workflow.vo;

import java.util.Date;

import com.zte.mcrm.system.common.run.system.BaseThread;

public class ThreadVO {
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.ROW_ID
     *
     * @mbggenerated
     */
    private String rowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.CREATED
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.CREATED_BY
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.LAST_UPD
     *
     * @mbggenerated
     */
    private Date lastUpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.LAST_UPD_BY
     *
     * @mbggenerated
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.MODIFICATION_NUM
     *
     * @mbggenerated
     */
    private Long modificationNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.CONFLICT_ID
     *
     * @mbggenerated
     */
    private String conflictId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.ACTL_END_DT
     *	结束日期
     * @mbggenerated
     */
    private Date actlEndDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.ACTL_START_DT
     *	实际开始时间
     * @mbggenerated
     */
    private Date actlStartDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.DB_LAST_UPD
     *
     * @mbggenerated
     */
    private Date dbLastUpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.EXPIRATION_DT
     *	到期时间
     * @mbggenerated
     */
    private Date expirationDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.SCHED_START_DT
     *	预计开始时间
     * @mbggenerated
     */
    private Date schedStartDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.SUBMIT_DATE
     *	提交日期
     * @mbggenerated
     */
    private Date submitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.CLASS_NAME
     *
     * @mbggenerated
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.COMPLETION_CD
     *	完成代码
     * @mbggenerated
     */
    private String completionCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.COMPLETION_TEXT
     *	完成信息
     * @mbggenerated
     */
    private String completionText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.DB_LAST_UPD_SRC
     *
     * @mbggenerated
     */
    private String dbLastUpdSrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.DESC_TEXT
     *
     * @mbggenerated
     */
    private String descText;//说明

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.EXEC_SRVR_NAME
     *	执行服务器
     * @mbggenerated
     */
    private String execSrvrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.METHOD
     *
     * @mbggenerated
     */
    private String method;//组件/作业

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.TMODEL
     *	模式
     * @mbggenerated
     */
    private String tmodel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.RPT_FLAG
     *	是否重复？
     * @mbggenerated
     */
    private String rptFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.RPT_INTERVAL
     *	重复间隔
     * @mbggenerated
     */
    private String rptInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.RPT_UOM
     *重复单位
     * @mbggenerated
     */
    private String rptUom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.STATUS
     *	状态
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SIEBEL.CX_THREAD_REQ.TASK_PID
     *	任务 ID
     * @mbggenerated
     */
    private String taskPid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.ROW_ID
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.ROW_ID
     *
     * @mbggenerated
     */
    public String getRowId() {
        return rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.ROW_ID
     *
     * @param rowId the value for SIEBEL.CX_THREAD_REQ.ROW_ID
     *
     * @mbggenerated
     */
    public void setRowId(String rowId) {
        this.rowId = rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.CREATED
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.CREATED
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.CREATED
     *
     * @param created the value for SIEBEL.CX_THREAD_REQ.CREATED
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.CREATED_BY
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.CREATED_BY
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.CREATED_BY
     *
     * @param createdBy the value for SIEBEL.CX_THREAD_REQ.CREATED_BY
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.LAST_UPD
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.LAST_UPD
     *
     * @mbggenerated
     */
    public Date getLastUpd() {
        return lastUpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.LAST_UPD
     *
     * @param lastUpd the value for SIEBEL.CX_THREAD_REQ.LAST_UPD
     *
     * @mbggenerated
     */
    public void setLastUpd(Date lastUpd) {
        this.lastUpd = lastUpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.LAST_UPD_BY
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.LAST_UPD_BY
     *
     * @mbggenerated
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.LAST_UPD_BY
     *
     * @param lastUpdBy the value for SIEBEL.CX_THREAD_REQ.LAST_UPD_BY
     *
     * @mbggenerated
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.MODIFICATION_NUM
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.MODIFICATION_NUM
     *
     * @mbggenerated
     */
    public Long getModificationNum() {
        return modificationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.MODIFICATION_NUM
     *
     * @param modificationNum the value for SIEBEL.CX_THREAD_REQ.MODIFICATION_NUM
     *
     * @mbggenerated
     */
    public void setModificationNum(Long modificationNum) {
        this.modificationNum = modificationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.CONFLICT_ID
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.CONFLICT_ID
     *
     * @mbggenerated
     */
    public String getConflictId() {
        return conflictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.CONFLICT_ID
     *
     * @param conflictId the value for SIEBEL.CX_THREAD_REQ.CONFLICT_ID
     *
     * @mbggenerated
     */
    public void setConflictId(String conflictId) {
        this.conflictId = conflictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.ACTL_END_DT
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.ACTL_END_DT
     *
     * @mbggenerated
     */
    public Date getActlEndDt() {
        return actlEndDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.ACTL_END_DT
     *
     * @param actlEndDt the value for SIEBEL.CX_THREAD_REQ.ACTL_END_DT
     *
     * @mbggenerated
     */
    public void setActlEndDt(Date actlEndDt) {
        this.actlEndDt = actlEndDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.ACTL_START_DT
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.ACTL_START_DT
     *
     * @mbggenerated
     */
    public Date getActlStartDt() {
        return actlStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.ACTL_START_DT
     *
     * @param actlStartDt the value for SIEBEL.CX_THREAD_REQ.ACTL_START_DT
     *
     * @mbggenerated
     */
    public void setActlStartDt(Date actlStartDt) {
        this.actlStartDt = actlStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.DB_LAST_UPD
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.DB_LAST_UPD
     *
     * @mbggenerated
     */
    public Date getDbLastUpd() {
        return dbLastUpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.DB_LAST_UPD
     *
     * @param dbLastUpd the value for SIEBEL.CX_THREAD_REQ.DB_LAST_UPD
     *
     * @mbggenerated
     */
    public void setDbLastUpd(Date dbLastUpd) {
        this.dbLastUpd = dbLastUpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.EXPIRATION_DT
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.EXPIRATION_DT
     *
     * @mbggenerated
     */
    public Date getExpirationDt() {
        return expirationDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.EXPIRATION_DT
     *
     * @param expirationDt the value for SIEBEL.CX_THREAD_REQ.EXPIRATION_DT
     *
     * @mbggenerated
     */
    public void setExpirationDt(Date expirationDt) {
        this.expirationDt = expirationDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.SCHED_START_DT
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.SCHED_START_DT
     *
     * @mbggenerated
     */
    public Date getSchedStartDt() {
        return schedStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.SCHED_START_DT
     *
     * @param schedStartDt the value for SIEBEL.CX_THREAD_REQ.SCHED_START_DT
     *
     * @mbggenerated
     */
    public void setSchedStartDt(Date schedStartDt) {
        this.schedStartDt = schedStartDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.SUBMIT_DATE
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.SUBMIT_DATE
     *
     * @mbggenerated
     */
    public Date getSubmitDate() {
        return submitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.SUBMIT_DATE
     *
     * @param submitDate the value for SIEBEL.CX_THREAD_REQ.SUBMIT_DATE
     *
     * @mbggenerated
     */
    public void setSubmitDate(Date submitDate) {
        this.submitDate = submitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.CLASS_NAME
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.CLASS_NAME
     *
     * @mbggenerated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.CLASS_NAME
     *
     * @param className the value for SIEBEL.CX_THREAD_REQ.CLASS_NAME
     *
     * @mbggenerated
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.COMPLETION_CD
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.COMPLETION_CD
     *
     * @mbggenerated
     */
    public String getCompletionCd() {
        return completionCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.COMPLETION_CD
     *
     * @param completionCd the value for SIEBEL.CX_THREAD_REQ.COMPLETION_CD
     *
     * @mbggenerated
     */
    public void setCompletionCd(String completionCd) {
        this.completionCd = completionCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.COMPLETION_TEXT
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.COMPLETION_TEXT
     *
     * @mbggenerated
     */
    public String getCompletionText() {
        return completionText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.COMPLETION_TEXT
     *
     * @param completionText the value for SIEBEL.CX_THREAD_REQ.COMPLETION_TEXT
     *
     * @mbggenerated
     */
    public void setCompletionText(String completionText) {
        this.completionText = completionText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.DB_LAST_UPD_SRC
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.DB_LAST_UPD_SRC
     *
     * @mbggenerated
     */
    public String getDbLastUpdSrc() {
        return dbLastUpdSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.DB_LAST_UPD_SRC
     *
     * @param dbLastUpdSrc the value for SIEBEL.CX_THREAD_REQ.DB_LAST_UPD_SRC
     *
     * @mbggenerated
     */
    public void setDbLastUpdSrc(String dbLastUpdSrc) {
        this.dbLastUpdSrc = dbLastUpdSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.DESC_TEXT
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.DESC_TEXT
     *
     * @mbggenerated
     */
    public String getDescText() {
        return descText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.DESC_TEXT
     *
     * @param descText the value for SIEBEL.CX_THREAD_REQ.DESC_TEXT
     *
     * @mbggenerated
     */
    public void setDescText(String descText) {
        this.descText = descText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.EXEC_SRVR_NAME
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.EXEC_SRVR_NAME
     *
     * @mbggenerated
     */
    public String getExecSrvrName() {
        return execSrvrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.EXEC_SRVR_NAME
     *
     * @param execSrvrName the value for SIEBEL.CX_THREAD_REQ.EXEC_SRVR_NAME
     *
     * @mbggenerated
     */
    public void setExecSrvrName(String execSrvrName) {
        this.execSrvrName = execSrvrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.METHOD
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.METHOD
     *
     * @mbggenerated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.METHOD
     *
     * @param method the value for SIEBEL.CX_THREAD_REQ.METHOD
     *
     * @mbggenerated
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.TMODEL
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.TMODEL
     *
     * @mbggenerated
     */
    public String getTmodel() {
        return tmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.TMODEL
     *
     * @param tmodel the value for SIEBEL.CX_THREAD_REQ.TMODEL
     *
     * @mbggenerated
     */
    public void setTmodel(String tmodel) {
        this.tmodel = tmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.RPT_FLAG
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.RPT_FLAG
     *
     * @mbggenerated
     */
    public String getRptFlag() {
        return rptFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.RPT_FLAG
     *
     * @param rptFlag the value for SIEBEL.CX_THREAD_REQ.RPT_FLAG
     *
     * @mbggenerated
     */
    public void setRptFlag(String rptFlag) {
        this.rptFlag = rptFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.RPT_INTERVAL
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.RPT_INTERVAL
     *
     * @mbggenerated
     */
    public String getRptInterval() {
        return rptInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.RPT_INTERVAL
     *
     * @param rptInterval the value for SIEBEL.CX_THREAD_REQ.RPT_INTERVAL
     *
     * @mbggenerated
     */
    public void setRptInterval(String rptInterval) {
        this.rptInterval = rptInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.RPT_UOM
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.RPT_UOM
     *
     * @mbggenerated
     */
    public String getRptUom() {
        return rptUom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.RPT_UOM
     *
     * @param rptUom the value for SIEBEL.CX_THREAD_REQ.RPT_UOM
     *
     * @mbggenerated
     */
    public void setRptUom(String rptUom) {
        this.rptUom = rptUom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.STATUS
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.STATUS
     *
     * @param status the value for SIEBEL.CX_THREAD_REQ.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SIEBEL.CX_THREAD_REQ.TASK_PID
     *
     * @return the value of SIEBEL.CX_THREAD_REQ.TASK_PID
     *
     * @mbggenerated
     */
    public String getTaskPid() {
        return taskPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SIEBEL.CX_THREAD_REQ.TASK_PID
     *
     * @param taskPid the value for SIEBEL.CX_THREAD_REQ.TASK_PID
     *
     * @mbggenerated
     */
    public void setTaskPid(String taskPid) {
        this.taskPid = taskPid;
    }
    

}